export default {
	'en-AU': {
		'action.edit': 'Edit',
		'action.view': 'View',
		'action.reset': 'Reset',
		'action.retry': 'Retry',
		'action.leave': 'Leave',
		'action.cancel': 'Cancel',
		'action.delete': 'Delete',
		'action.remove': 'Remove',
		'action.search': 'Search',
		'action.finish': 'Finish',
		'action.manage': 'Manage',
		'action.go_home': 'Go Home',
		'action.duplicate': 'Duplicate',
		'action.get_support': 'Get Support',
		'action.choose_file': 'Choose File',
		'action.edit_profile': 'Edit Profile',
		'action.view_profile': 'View Profile',
		'action.save_changes': 'Save Changes',
		'action.create_account': 'Create Account',
		'action.view_roblox_link': 'View Roblox Link',

		'label.none': 'None',
		'label.disabled': 'Disabled',
		'label.roblox_link_id': 'Link ID: {0}',
		'label.roblox_link_deleted': 'This Roblox Link was recently deleted, and can no longer be viewed.',

		'home': 'Home',
		'home.landing': 'under construction...',

		'profile.id': 'User ID: {0}',
		'profile.bio': 'Bio',
		'profile.bio.empty': 'Tell the world what you\'re all about!',
		'profile.name': 'Display Name',
		'profile.avatar': 'Avatar',
		'profile.joined': 'Joined {0|time_ago}',
		'profile.roblox': 'Known on Roblox as:',
		'profile.burger.true': 'You have already burger\'d this user.',
		'profile.burger.false': 'Tell this user they\'re burgers!',
		'profile.username': 'Username',
		'profile.teams.false': 'Part of {0|number} teams:',
		'profile.teams.true': 'Part of a team:',
		'profile.teams.item.details': '{0} Member{0|s} • {1} is {2}',

		'avatar_file.size': 'Image should be at least 256x256.',

		'team.id': 'Team ID: {0}',
		'team.joined': 'Created {0|time_ago}',
		'team.members': 'Members',
		'team.projects': 'Projects',

		'team.settings.profile': 'Profile',
		'team.settings.profile.header': 'Team Profile',
		'team.settings.profile.name': 'Team Name',
		'team.settings.archive': 'Archive',
		'team.settings.archive.audit_log': 'Audit Log',

		'members': '{0} Member{0|s}',

		'project.author.0': 'by ',
		'project.author.1': ', and {0} contributor{0|s}',
		'project.archived': 'This project has been archived as of {0|date}.',
		'project.website': 'Visit Website',
		'project.github': 'GitHub Repository',
		'project.about': 'About this project',
		'project.about.empty': '# {0.display_name}\nThe authors of this project haven\'t written a description yet...',
		'project.about.empty.github': '<br/>Perhaps try visiting the [GitHub Repository]({0.github_url}) for more information!',
		'project.contributors': 'Contributors',
		'project.contributors.count': '{0} Contributor{0|s}',
		'project.contributors.external': '... plus {0} external contributor{0|s}.',
		'project.id': 'Project ID: {0}',

		'team_role.0': 'Team Member',
		'team_role.0.profile': 'a member',
		'team_role.200': 'Team Administrator',
		'team_role.200.profile': 'an administrator',
		'team_role.255': 'Team Owner',
		'team_role.255.profile': 'the owner',

		'user_role.2': 'Staff',
		'user_role.4': 'Tester',

		'roblox_link.flag.0': 'Confirmation Needed',
		'roblox_link.flag.2': 'Verified',
		'roblox_link.visible.true': 'Public, will be displayed on your profile, and available via the Rest API.',
		'roblox_link.visible.false': 'Private, only you and your connected services can see this.',
		'roblox_link.view': 'View on Roblox',
		'roblox_link.primary': 'Primary',
		'roblox_link.make_primary': 'Make Primary',
		'roblox_link.change_visibility.true': 'Make Private',
		'roblox_link.change_visibility.false': 'Make Public',
		'roblox_link.delete': 'Unlink Account',

		'user_action.user.profile': 'Your Profile',
		'user_action.user.teams': 'Your Teams',
		'user_action.settings': 'Settings',
		'user_action.other.logout': 'Sign out',

		'login.github' : 'Continue with GitHub',
		'login.discord': 'Continue with Discord',

		'signup': 'Create an Account',

		'create_profile': 'Set-up your profile',
		'create_profile.username': 'Enter username',
		'create_profile.finish': 'Create Profile',
		'create_profile.error': 'An error occurred.',

		'platform.0': 'Discord',

		'roblox.verification.finish': 'Is this your Roblox account?',
		'roblox.verification.finish.sub': 'Joined {0|time_ago} • Identifier: {1}',
		'roblox.verification.finish.yes': 'Confirm & Proceed',
		'roblox.verification.finish.no': 'Change Account',

		'settings': 'Your Account',
		'settings.account': 'Account',

		'settings.access': 'Access',
		'settings.access.teams': 'Teams',

		'settings.roblox': 'Roblox Settings',
		'settings.roblox.accounts': 'Linked Accounts',
		'settings.roblox.accounts.help': 'Having troubles? Join our Discord Server & ask our staff members for assistance!',
		'settings.roblox.accounts.list': 'Linked Roblox Accounts',
		'settings.roblox.accounts.add': 'Link Roblox Account',
		'settings.roblox.accounts.mellow': 'It appears that you signed-up via mellow, you can now close this page, and return to Discord.',

		'settings.mellow': 'mellow Settings',
		'settings.mellow.servers': 'Discord Servers',
		'settings.mellow.servers.add': 'Need to connect a Discord Server? Use mellow\'s /connect command in your server of choice.',
		'settings.mellow.servers.server.members': 'Managed by {0} user{0|s}',
		'settings.mellow.servers.server.placeholder': 'Unknown status, check back later.',
		'settings.mellow.servers.refresh': 'Refresh Discord Servers',

		'mellow.server.settings.audit_log': 'Audit Log',

		'mellow.server.settings.commands.custom': 'Custom Commands',

		'mellow.server.settings.logging': 'Logging',
		'mellow.server.settings.logging.channel': 'Logging Channel',
		'mellow.server.settings.logging.channel.category': 'Discord Channels',
		'mellow.server.settings.logging.types': 'Actions to log',

		'mellow.server.settings.roblox': 'Roblox',
		'mellow.server.settings.roblox.global': 'Global Settings',
		'mellow.server.settings.roblox.global.nickname': 'Default Nickname',
		'mellow.server.settings.roblox.global.nickname.summary': 'This nickname will be applied to users with a verified Roblox Account if they do not meet the requirements of a nickname link.\nInstances of {name} will be replaced with the user\'s Roblox Display Name.',
		'mellow.server.settings.roblox.global.nickname.placeholder': 'Leave empty to disable',
		'mellow.server.settings.roblox.global.nickname.long': 'Long display names will cause the nickname to be truncated.',
		'mellow.server.settings.roblox.binds': 'Links',
		'mellow.server.settings.roblox.binds.create': 'Create New Link',
		'mellow.server.settings.roblox.binds.import': 'Import Links',
		'mellow.server.settings.roblox.binds.import.category': 'Import Types',
		'mellow.server.settings.roblox.binds.import.type.0': 'Roblox Group Roles → Discord Roles',
		'mellow.server.settings.return': 'Return to Server List',

		'mellow_link_editor.header.false': 'Create Link',
		'mellow_link_editor.header.true': 'Update Existing Link',
		'mellow_link_editor.name': 'Name',
		'mellow_link_editor.type': 'Link to',
		'mellow_link_editor.type.category': 'Link Types',
		'mellow_link_editor.discord_roles': 'Discord Roles (Click to remove)',
		'mellow_link_editor.discord_roles.category': 'Server Roles',
		'mellow_link_editor.discord_roles.options': 'Other Options',
		'mellow_link_editor.discord_roles.add_all': 'Add All Roles',
		'mellow_link_editor.group.details': '{0.memberCount} Member{0.memberCount|s} • {0.id}',
		'mellow_link_editor.group_role.details': '{0.memberCount} User{0.memberCount|s} • Rank {0.rank} • {0.id}',
		'mellow_link_editor.requirements': 'Requirements',
		'mellow_link_editor.requirements.add': 'Add Requirement',
		'mellow_link_editor.requirement': 'Requirement',
		'mellow_link_editor.requirement.group': 'Group',
		'mellow_link_editor.requirement.group_role': 'Group Role',
		'mellow_link_editor.requirement.group_role.placeholder': 'Select a Role',
		'mellow_link_editor.requirement.rank_from': 'From',
		'mellow_link_editor.requirement.rank_to': 'To',
		'mellow_link_editor.requirement.link': 'Roblox Link',
		'mellow_link_editor.requirement.link.placeholder': 'Select a Link',
		'mellow_link_editor.finish': 'Create Link',

		'mellow_server_audit_log.type.0': 'added this server to mellow',
		'mellow_server_audit_log.type.1': 'created a Roblox Link named "{0.data.name}"',
		'mellow_server_audit_log.type.2': 'updated the Global Roblox Settings',
		'mellow_server_audit_log.type.2.default_nickname': 'Default Nickname Changes',
		'mellow_server_audit_log.type.3': 'deleted a Roblox Link named "{0.data.name}"',
		'mellow_server_audit_log.type.4': 'updated the "{0.data.name.0}" Roblox Link',
		'mellow_server_audit_log.type.4.name': 'Name Changes',
		'mellow_server_audit_log.type.4.type': 'Type Changes',
		'mellow_server_audit_log.type.4.target_ids': 'Set {0.data.target_ids} targets',
		'mellow_server_audit_log.type.4.requirements': 'Set {0.data.requirements} requirements',
		'mellow_server_audit_log.type.4.requirements_type': 'Requirements Type Changes',
		'mellow_server_audit_log.type.5': 'updated logging settings',
		'mellow_server_audit_log.type.5.types': 'Enabled Actions Changes',
		'mellow_server_audit_log.type.5.channel': 'Target Channel Changes',

		'mellow_server_logging_type.0': '',
		'mellow_server_logging_type.1': 'Mellow Audit Log',
		'mellow_server_logging_type.2': 'Server Profile Sync',

		'team_audit_log.type.0': 'created the team',
		'team_audit_log.type.1': 'renamed the team from "{0.data.0}" to "{0.data.1}"',
		'team_audit_log.type.2': 'changed the team avatar',
		'team_audit_log.type.3': 'modified the team profile',
		'team_audit_log.type.4': 'created a new project named "{0.data.name}"',
		'team_audit_log.type.5': 'modified the PLACEHOLDER project',
		'team_audit_log.type.6': 'changed the PLACEHOLDER project\'s avatar',
		'team_audit_log.type.7': 'changed the PLACEHOLDER project\'s banner',

		'user_notification.type.0': 'Team Invite',
		'user_notification.type.0.summary': 'You have been invited to join {0.target_team.display_name}',
		'user_notification.type.0.footer': 'invited by {1}.',
		'user_notification.type.1': 'Removed from Team',
		'user_notification.type.1.summary': 'You have been removed from {0.target_team.display_name}',
		'user_notification.type.1.footer': '',
		'user_notification.type.2': 'Roblox Account Removed',
		'user_notification.type.2.summary': 'Your link to @{0.data.name} has been invalidated',
		'user_notification.type.2.footer': '...a moderator was here!',
		'user_notification.type.3': 'SOMETHING',
		'user_notification.type.3.summary': '{1} thinks you\'re burgers!',
		'user_notification.type.3.footer': 'burgers burgers burgers 🍔🍔🍔',
		'user_notification.type.4': 'New Team Member',
		'user_notification.type.4.summary': '{1} has joined {0.target_team.display_name}',
		'user_notification.type.4.footer': '',
		'user_notification.type.5': 'Team Member Left',
		'user_notification.type.5.summary': '{1} has left {0.target_team.display_name}',
		'user_notification.type.5.footer': '',

		'notifications': 'Notifications ({0} total, {1} unread)',
		'notifications.empty': 'You\'re already up-to-date, nice!\n(～￣▽￣)～  no worries...',
		'notifications.read_all': 'Mark all as Read',
		'notifications.clear': 'Clear Notifications',

		'group_select': 'Select Group',
		'group_select.recent': 'Recent Groups',
		'group_select.search': 'Search for Group',
		'group_select.enter': 'Enter your query',
		'group_select.searching': 'Searching...',
		'group_select.empty': 'Nothing, try editing your query',
		'group_select.select': 'Select a Group',
		'group_select.results': '{0} Item{0|s}',
		'group_select.back': 'Back to Recent',

		'mellow_bind.type.0': 'Discord Roles',
		'mellow_bind.bound.0': 'Linked to {0} Discord Role{0|s}',
		'mellow_bind.creator': 'Created by',
		'mellow_bind.edited': ', edited by',
		'mellow_bind.view_mode.0': 'Default View',
		'mellow_bind.view_mode.1': 'Compact View',
		'mellow_bind.requirement.0': 'Must have a Verified Roblox Account',
		'mellow_bind.requirement.1': 'Must have a Roblox Group Role',
		'mellow_bind.requirement.2': 'Must have a Roblox Group Rank in range',
		'mellow_bind.requirement.3': 'Must be in a Roblox Group',
		'mellow_bind.requirement.4': 'Must be friends with someone',
		'mellow_bind.requirement.5': 'Must meet another link',
		'mellow_bind.requirements_type.0': 'Must meet all',
		'mellow_bind.requirements_type.1': 'Must meet at least one',
		'mellow_bind.requirements': '{0} Requirement{0|s}',
		'mellow_bind.requirements.with': 'with {0} requirement{0|s}',
		'mellow_bind.explanation.0': 'Users receive {0.length} Discord Role{0.length|s}',
		'mellow_bind.explanation.end.0': ' if they meet {0} requirement{0|s}.',
		'mellow_bind.explanation.end.1': ' if they meet at least one of {0} requirement{0|s}.',

		'error.page': '(。>︿<)_θ',
		'error.page2': 'oh noes, something\'s wrong!',
		'error.page3': 'Code {0} • ″{1}‶',
		'error.unknown': 'An unknown error occurred.',

		'request_error.0': 'There were issues with your request, please change your input and try again.',
		'request_error.1': 'You are not signed-in.',
		'request_error.2': 'An unexpected error occurred while updating our database, please try again in a few minutes.',
		'request_error.3': 'One of the requirements is missing its group value.',
		'request_error.4': 'Check your internet connection, refresh the page, or try again.',
		'request_error.5': 'This error can\'t be recognised, or hasn\'t been implemented yet.',
		'request_error.6': 'You don\'t have permission to access this resource.',
		'request_error.7': 'An unexpected error occurred while making a request to an external source, please try again in a few minutes.',
		'request_error.8': 'The requested resource could not be found.',
		'request_error.unauthorised': 'You don\'t have permission to access this resource.',
		'request_error.invalid_body': 'There were issues with your request, please change your input and try again.',
		'request_error.database_error': 'An unexpected error occurred while updating our database, please try again in a few minutes.',
		'request_error.profile_exists': 'Your account already has a profile set-up, try refreshing.',
		'request_error.title': 'REQUEST ERROR',
		'request_error.zod': 'ISSUES',

		'zod_issue.invalid_type': 'Received type is incorrect.',
		'zod_issue.invalid_literal': 'Received literal is incorrect.',
		'zod_issue.unrecognized_keys': 'Contains unrecognisable data.',
		'zod_issue.invalid_union': 'Received data is invalid.',
		'zod_issue.invalid_union_discriminator': 'Received data is invalid.',
		'zod_issue.invalid_enum_value': 'Received invalid value.',
		'zod_issue.invalid_arguments': 'Contains invalid data.',
		'zod_issue.invalid_return_type': 'Received data is invalid.',
		'zod_issue.invalid_date': 'Invalid date.',
		'zod_issue.invalid_string': 'Contains invalid characters.',
		'zod_issue.too_small': 'Contains less than {0.minimum} character{0.minimum|s}.',
		'zod_issue.too_big': 'Contains more than {0.maximum} character{0.maximum|s}.',
		'zod_issue.invalid_intersection_types': 'Received data is invalid.',
		'zod_issue.not_multiple_of': 'Received data is invalid.',
		'zod_issue.not_finite': 'Received data is invalid.',
		'zod_issue.custom': 'Received data is invalid.',

		'number': '{0|number}',

		'time_ago': '{0|time_ago}',
		'time_ago.0_0': '{0} seconds ago',
		'time_ago.0_1': 'now',
		'time_ago.1_0': '{0} minutes ago',
		'time_ago.1_1': '{0} minute ago',
		'time_ago.2_0': '{0} hours ago',
		'time_ago.2_1': '{0} hour ago',
		'time_ago.3_0': '{0} days ago at {1}:{2} {3}',
		'time_ago.3_1': 'yesterday',
		'time_ago.4_0': '{0} months ago',
		'time_ago.4_1': 'last month',
		'time_ago.5_0': '{0} years ago',
		'time_ago.5_1': 'last year',
		'time_ago.created': 'Created {0|time_ago}',
		'time_ago.updated': 'Updated {0|time_ago}',
		'time_ago.archived': 'Archived {0|time_ago}',

		'footer.oss': 'Voxelified is',
		'footer.oss.link': 'open-source',
		'footer.resources': 'Resources',
		'footer.community': 'Community'
	}
};