export default {
	'en-AU': {
		'143': '143',
		
		'action.edit': 'Edit',
		'action.next': 'Next',
		'action.view': 'View',
		'action.clone': 'Clone',
		'action.reset': 'Reset',
		'action.retry': 'Retry',
		'action.leave': 'Leave',
		'action.later': 'Later',
		'action.accept': 'Accept',
		'action.cancel': 'Cancel',
		'action.create': 'Create',
		'action.delete': 'Delete',
		'action.remove': 'Remove',
		'action.reject': 'Reject',
		'action.revoke': 'Revoke',
		'action.follow': 'Follow',
		'action.search': 'Search',
		'action.finish': 'Finish',
		'action.manage': 'Manage',
		'action.copy_id': 'Copy ID',
		'action.sign_in': 'Sign in',
		'action.go_home': 'Go Home',
		'action.preview': 'Preview',
		'action.continue': 'Continue',
		'action.transfer': 'Transfer',
		'action.unfollow': 'Unfollow',
		'action.duplicate': 'Duplicate',
		'action.try_again': 'Try Again',
		'action.disconnect': 'Disconnect',
		'action.leave_team': 'Leave Team',
		'action.create_new': 'Create New',
		'action.change_role': 'Change Role',
		'action.invite_team': 'Invite to Team',
		'action.acknowledge': 'Acknowledge',
		'action.get_support': 'Get Support',
		'action.choose_file': 'Choose File',
		'action.edit_profile': 'Edit Profile',
		'action.view_profile': 'View Profile',
		'action.save_changes': 'Save Changes',
		'action.return_from_mellow': 'Return to HAKUMI',
		'action.view_profile_sync_action': 'View Profile Sync Action',

		'label.by': 'by',
		'label.none': 'None',
		'label.events': '{0} Event{0|s}',
		'label.reason': 'Reason',
		'label.advanced': 'Advanced',
		'label.disabled': 'Disabled',
		'label.optional': 'Optional',
		'label.overview': 'Overview',
		'label.required': 'Required',
		'label.team_roles': 'Team Roles',
		'label.you_monster': 'You',
		'label.permissions': 'Permissions',
		'label.user_reason': 'User-facing Reason',
		'label.requirements': 'Requirements',
		'label.audit_reason': 'Reason for Audit Log',
		'label.requirements2': '{0} requirement{0|s}',
		'label.search.members': 'Search Members',
		'label.copyrighted_joke': 'That\'s all, folks!',
		'label.originally_created_by': 'Originally created by',
		'label.profile_sync_action_id': 'Action ID: {0}',
		'label.profile_sync_action_deleted': 'This Profile Sync Action was recently deleted, and can no longer be viewed.',

		'sort_by': 'Sort by',
		'sort_by.name': 'Name',
		'sort_by.join_date': 'Join Date',

		'home': 'Home',
		'home.landing': 'a hit new website under construction...',
		'home.landing.sub': 'one day, there will be something of interest on this page!',

		'profile_post.posted': 'posted {0|time_ago}',
		'profile_post.replied': 'replied {0|time_ago}',
		'profile_post.replied2': 'replied to',
		'profile_post.comments': 'Replies',
		'profile_post.comments.count': '{0|number} Replies',
		'profile_post.like.true': 'Unlike',
		'profile_post.like.false': 'Like',
		'profile_post.likes.count': '{0|number} Likes',

		'profile.id': 'User ID: {0}',
		'profile.posts': 'Posts ({0|number})',
		'profile.posts.create': 'Post',
		'profile.posts.create.placeholder': 'Tell everyone what\'s up!',
		'profile.posts.reply': 'Reply',
		'profile.posts.reply.placeholder': 'Reply with what you\'re thinking!',
		'profile.bio': 'Bio',
		'profile.bio.empty': 'Tell the world what you\'re all about!',
		'profile.bio.empty.team': 'Tell the world what your team is all about!',
		'profile.name': 'Display Name',
		'profile.avatar': 'Profile Picture',
		'profile.joined': 'Joined {0|time_ago}',
		'profile.burger.true': 'You have already burger\'d this user.',
		'profile.burger.false': 'Tell this user they\'re burgers!',
		'profile.username': 'Username',
		'profile.teams': 'Teams ({0|number})',
		'profile.teams.item.details': '{2} • {0} Member{0|s}',
		'profile.invite': 'Teams you can invite this user to',
		'profile.followers': '{0} Follower{0|s}',

		'avatar_file.size': 'Image should be at least 256x256.',

		'team.id': 'Team ID: {0}',
		'team.owner.false': 'Owned by no-one!',
		'team.owner.true': 'Owned by',
		'team.owner.none': 'Unowned',
		'team.created.false': 'Created {0|time_ago}',
		'team.created.true': 'Created {0|time_ago} by',
		'team.affiliations': 'Affiliated with',
		'team.members': 'Members ({0})',

		'team.invite': 'Welcome to {0}',
		'team.invite.summary': 'This page is currently unfinished, and will pop into existence at a later date!',
		'team.invite.done': 'Complete Setup',
		'team.invite.skip': 'Skip this step',

		'team.settings.profile': 'Profile',
		'team.settings.profile.header': 'Team Profile',
		'team.settings.profile.name': 'Team Handle',
		'team.settings.profile.display_name': 'Team Name',
		'team.settings.profile.website_url': 'Website URL',
		'team.settings.profile.delete': 'Delete Team',
		'team.settings.access': 'Access',
		'team.settings.access.members': 'Members',
		'team.settings.access.members.tab': 'Members ({0})',
		'team.settings.access.members.invites': 'Pending Invitations ({0})',
		'team.settings.access.members.invites.tip': 'You can invite people to the team by going to their profile, and tapping on the options menu.',
		'team.settings.access.roles': 'Roles',
		'team.settings.access.roles.summary': 'Use roles to group your team members and assign permissions.',
		'team.settings.access.roles.return': 'Return to Roles',
		'team.settings.archive': 'Archive',
		'team.settings.developer': 'Developer',
		'team.settings.developer.applications': 'Applications',

		'team_invite.author': 'Invited by',
		'team_invite.author2': 'invited by',

		'members': '{0} Member{0|s}',

		'team_role.unknown': 'No Role',

		'team_role_permission.0': '',
		'team_role_permission.1': 'Manage Team',
		'team_role_permission.2': 'Invite Users',
		'team_role_permission.4': 'Manage Members',
		'team_role_permission.8': 'Manage Roles',
		'team_role_permission.16': 'All Permissions (Dangerous!)',

		'mellow_webhook_event.0': '',
		'mellow_webhook_event.1': 'Server Profile Synced',

		'user_role.2': 'Staff',
		'user_role.4': 'Tester',

		'user_action.user.profile': 'Your Profile',
		'user_action.user.teams': 'Your Teams',
		'user_action.settings': 'Settings',
		'user_action.other.logout': 'Sign out',

		'signin.manual': 'Sign in to your HAKUMI account',
		'signin.manual.name': 'Enter your creative username',
		'signin.signup': 'Create an account',

		'signup': 'Create a HAKUMI account',
		'signup.name': 'Enter a creative username!',
		'signup.name_error.1': 'Add {0} more character{0|s} to that!',
		'signup.continue': 'Join HAKUMI!',
		'signup.signin': 'Already have an account?',

		'create_profile': 'Set-up your profile',
		'create_profile.username': 'Enter username',
		'create_profile.finish': 'Create Profile',
		'create_profile.error': 'An error occurred.',

		'settings': 'Your Account',
		'settings.profile': 'Your Profile',
		'settings.profile.summary': 'This is your very own profile, customise it, and whatever!',

		'settings.account.username': 'Username',
		'settings.account.username.summary': 'This is your namespace within HAKUMI.',
		'settings.account.id': 'HAKUMI ID',
		'settings.account.id.summary': 'This is your unique identifier within HAKUMI, it cannot be changed.',

		'settings.account.connections': 'Connections',
		'settings.account.connections.summary': 'Connect your HAKUMI Account with a third-party service to display it on your profile, or use it for other features.',
		'settings.account.connections.add': 'Add New',
		'settings.account.connections.add.exists': 'You already have an existing {0} connection. Remove it to add a new one.',

		'settings.access': 'Access',
		'settings.access.security': 'Security',
		'settings.access.security.devices': 'Passkeys',
		'settings.access.security.devices.summary': 'Passkeys are your only method of sign in, remove any that you no longer use or don\'t recognise.',
		'settings.access.security.device.registered': 'Registered on {0} using {1}',
		'settings.access.security.device.registered.origin': 'in {0}',
		'settings.access.security.device.last_used': 'Last used {0|time_ago}',
		'settings.access.security.create': 'Create new Passkey',
		'settings.access.security.create.name': 'Name your Passkey',
		'settings.access.teams': 'Teams',
		'settings.access.teams.create': 'Create New Team',
		'settings.access.teams.create.header': 'Set-up your team',
		'settings.access.teams.create.name': 'Team Name',
		'settings.access.teams.create.avatar': 'Profile Picture',

		'settings.mellow': 'mellow Settings',
		'settings.mellow.servers': 'mellow Servers',
		'settings.mellow.servers.add': 'You can execute mellow\'s /setup command within a Discord server to start configuring it here.',
		'settings.mellow.servers.server.members': 'Managed by {0} user{0|s}',
		'settings.mellow.servers.server.placeholder': 'Unknown status, check back later.',
		'settings.mellow.servers.refresh': 'Refresh Discord Servers',

		'settings.integrations': 'Integrations',
		'settings.integrations.applications': 'Applications',
		'settings.integrations.applications.summary': 'This is a list of applications that you have authorised to access certain aspects of your account.',

		'mellow.server.0': 'Server',
		'mellow.server.1': 'Profile Sync Actions',
		'mellow.server.2': 'Settings',

		'mellow.server.settings': 'Server Settings',
		'mellow.server.settings.0': 'General',
		'mellow.server.settings.1': 'Logging',
		'mellow.server.settings.2': 'Syncing',
		'mellow.server.settings.3': 'Webhooks',
		'mellow.server.settings.4': 'Action Log',

		'mellow.server.settings.general.transfer': 'Transfer to Team',
		'mellow.server.settings.general.transfer.summary': 'Transferring this server to a Team will allow you to assign members to manage this server.',
		'mellow.server.settings.general.transfer.already_team': 'This server is currently being managed by members of {0}.',

		'mellow.server.settings.automation': 'Automation',
		'mellow.server.settings.automation.logging.channel': 'Logging Channel',
		'mellow.server.settings.automation.logging.channel.category': 'Discord Channels',
		'mellow.server.settings.automation.logging.types': 'Actions to log',
		'mellow.server.settings.automation.webhooks': 'Webhooks',
		'mellow.server.settings.automation.webhooks.summary': 'Webhooks allow external services to be notified when certain events happen.',
		'mellow.server.settings.automation.webhooks.create': 'Create New Webhook',

		'mellow.server.settings.syncing.actions.header': 'Profile Sync Actions',
		'mellow.server.settings.syncing.actions.summary': 'Actions allow you to manage members based on information from external services.\nFor example, you could have an action that gives a member a role if they\'re in a Roblox Group.',
		'mellow.server.settings.syncing.actions.create': 'Create New Action',
		'mellow.server.settings.syncing.settings': 'Settings',
		'mellow.server.settings.syncing.settings.nickname': 'Default Nickname',
		'mellow.server.settings.syncing.settings.nickname.summary': 'This nickname will be applied to members if they do not meet the requirements of a nickname action.',
		'mellow.server.settings.syncing.settings.nickname.placeholder': 'Leave empty to disable',
		'mellow.server.settings.syncing.settings.nickname.long': 'Long display names will cause the nickname to be truncated.',
		'mellow.server.settings.syncing.settings.skip_onboarding': 'New User Process',
		'mellow.server.settings.syncing.settings.skip_onboarding.default': 'Onboarding',
		'mellow.server.settings.syncing.settings.skip_onboarding.connect': 'Connect with {0}',
		'mellow.server.settings.syncing.settings.other': 'Advanced Settings',
		'mellow.server.settings.syncing.settings.sync_unknown_users': 'Sync Unknown Users',
		'mellow.server.settings.syncing.settings.allow_forced_syncing': 'Allow Forced Syncing',
		'mellow.server.settings.return': 'Return to Server List',

		'mellow.server.settings.api': 'Rest API',
		'mellow.server.settings.api.title': 'Rest API Settings',
		'mellow.server.settings.api.summary': 'The HAKUMI Rest API allows you to fetch information about members.',
		'mellow.server.settings.api.key': 'API Key',
		'mellow.server.settings.api.key.summary': 'All server endpoints require an API Key for every request.',
		'mellow.server.settings.api.key.new': 'Here is your new API Key, be very careful with it... {0}',
		'mellow.server.settings.api.key.exists': 'An API Key for {0} already exists, it was requested {1|time_ago}. Generating a new key will invalidate the existing key.',
		'mellow.server.settings.api.key.generate': 'Generate new API Key',

		'mellow.server.member.connections': '{0}\'s Server Connections',
		'mellow.server.member.connections.summary': 'This list contains all connections that {0} has set for this server.',

		'mellow_link_editor.header.false': 'Create Action',
		'mellow_link_editor.header.true': 'Update Existing Action',
		'mellow_link_editor.name': 'Name',
		'mellow_link_editor.type': 'Member Action',
		'mellow_link_editor.type.category': 'Actions',
		'mellow_link_editor.discord_roles': 'Discord Roles',
		'mellow_link_editor.discord_roles.placeholder': 'Select one or more',
		'mellow_link_editor.discord_roles.category': 'Server Roles',
		'mellow_link_editor.requirements': 'Member Requirements',
		'mellow_link_editor.requirements.add': 'Add Requirement',
		'mellow_link_editor.requirements.platforms': 'Platform-specific Requirements',
		'mellow_link_editor.requirements.platforms.0': 'Roblox',
		'mellow_link_editor.requirements.platforms.1': 'GitHub',
		'mellow_link_editor.requirements.platforms.2': 'Steam',
		'mellow_link_editor.requirements.platforms.3': 'HAKUMI',
		'mellow_link_editor.requirements.platforms.4': 'Other',
		'mellow_link_editor.requirements.other': 'Other Requirements',
		'mellow_link_editor.requirement': 'Requirement',
		'mellow_link_editor.requirement.group': 'Group',
		'mellow_link_editor.requirement.group_role': 'Group Role',
		'mellow_link_editor.requirement.group_role.placeholder': 'Select a role',
		'mellow_link_editor.requirement.rank_from': 'From',
		'mellow_link_editor.requirement.rank_to': 'To',
		'mellow_link_editor.requirement.link.placeholder': 'Select an action',
		'mellow_link_editor.finish': 'Create Link',

		'action_log.type.team.created': 'created the team',
		'action_log.type.team.renamed': 'renamed the team from **{0.data.0}** to **{0.data.1}**',
		'action_log.type.team.avatar.updated': 'updated the team\'s avatar',
		'action_log.type.team.public_profile.updated': 'updated the team\'s public profile',
		'action_log.type.team.role.created': 'created {team_role}',
		'action_log.type.team.role.updated': 'updated {team_role}',
		'action_log.type.team.role.deleted': 'deleted {team_role}',
		'action_log.type.team.member.updated': 'updated {user}',
		'action_log.type.team.member.removed': 'removed {user} from the team',
		'action_log.type.team.member_invitation.created': 'invited {user} to the team',
		'action_log.type.team.mellow_server.transferred.to_here':  'transferred ownership of {mellow_server} to this team',

		'action_log.type.mellow.server.created': 'added this server',
		'action_log.type.mellow.server.webhook.created': 'created {mellow_webhook}',
		'action_log.type.mellow.server.webhook.updated': 'updated {mellow_webhook}',
		'action_log.type.mellow.server.webhook.deleted': 'deleted {mellow_webhook}',
		'action_log.type.mellow.server.api_key.created': 'created a new API Key',
		'action_log.type.mellow.server.syncing.action.created': 'created {mellow_sync_action}',
		'action_log.type.mellow.server.syncing.action.updated': 'updated {mellow_sync_action}',
		'action_log.type.mellow.server.syncing.action.deleted': 'deleted {mellow_sync_action}',
		'action_log.type.mellow.server.syncing.settings.updated': 'updated the syncing settings',
		'action_log.type.mellow.server.discord_logging.updated': 'updated Discord logging settings',
		'action_log.type.mellow.server.ownership.changed': 'transferred ownership to {unimplemented}',

		'action_log.unknown_user': 'Unknown User',
		'action_log.unknown_webhook': 'Unknown Webhook',
		'action_log.unknown_team_role': 'Unknown Role',
		'action_log.unknown_mellow_action': 'Unknown Action',

		'mellow_server_logging_type.0': '',
		'mellow_server_logging_type.1': 'Mellow Audit Log',
		'mellow_server_logging_type.2': 'Server Profile Sync',

		'mellow_default_nickname.{roblox_username}': 'Roblox Username',
		'mellow_default_nickname.{roblox_display_name}': 'Roblox Display Name',
		'mellow_default_nickname.': 'Disabled',

		'user_notification.type.0': 'Team Invite',
		'user_notification.type.0.summary': 'You have been invited to join {0.target_team.display_name}',
		'user_notification.type.0.footer': 'invited by {1}.',
		'user_notification.type.1': 'Removed from Team',
		'user_notification.type.1.summary': 'You have been removed from {0.target_team.display_name}',
		'user_notification.type.1.footer': '',
		'user_notification.type.2': 'User Connection Removed',
		'user_notification.type.2.summary': 'Your connection to PLACEHOLDER has been moderated',
		'user_notification.type.2.footer': '',
		'user_notification.type.3': 'SOMETHING',
		'user_notification.type.3.summary': '{1} thinks you\'re burgers!',
		'user_notification.type.3.footer': 'burgers burgers burgers 🍔🍔🍔',
		'user_notification.type.4': 'New Team Member',
		'user_notification.type.4.summary': '{1} has joined {0.target_team.display_name}',
		'user_notification.type.4.footer': '',
		'user_notification.type.5': 'Team Member Left',
		'user_notification.type.5.summary': '{1} has left {0.target_team.display_name}',
		'user_notification.type.5.footer': '',
		'user_notification.type.6': 'Post Liked',
		'user_notification.type.6.summary': '{1} liked one of your posts!',
		'user_notification.type.6.footer': '',

		'user_connection.type.0': 'Discord',
		'user_connection.type.0.manage': 'Manage on discord.com',
		'user_connection.type.1': 'GitHub',
		'user_connection.type.1.manage': 'Manage on github.com',
		'user_connection.type.2': 'Roblox',
		'user_connection.type.2.manage': 'Manage on roblox.com',
		'user_connection.created': 'Connected {0|time_ago}',

		'application.last_used': 'Last used {0|time_ago}',

		'notifications': 'Notifications ({0} total, {1} unread)',
		'notifications.empty': 'You\'re already up-to-date, nice!\n(～￣▽￣)～  no worries...',
		'notifications.read_all': 'Mark all as Read',
		'notifications.clear': 'Clear Notifications',

		'enable_sudo_mode': 'Confirm Access',
		'enable_sudo_mode.summary': 'We need to confirm that you\'re the owner of this account.\nWhen you are ready, authenticate using the button below.',
		'enable_sudo_mode.continue': 'Use Passkey',

		'group_select': 'Select a group',
		'group_select.team': 'Select a team',
		'group_select.recent': 'Recent Groups',
		'group_select.search': 'Search for Group',
		'group_select.enter': 'Enter your query',
		'group_select.searching': 'Searching...',
		'group_select.empty': 'Nothing, try editing your query',
		'group_select.select': 'Select a Group',
		'group_select.results': '{0} Item{0|s}',
		'group_select.back': 'Back to Recent',

		'mellow_onboarding.server': 'Welcome to {0}!',
		'mellow_onboarding.server.sub': 'Before you continue, please review the section below.',
		'mellow_onboarding.connections': 'Recommended connections',
		'mellow_onboarding.connections.sub': 'This server utilises the following services to base your server profile on.\nCheck the server for details if you aren\'t sure what\'s required.',
		'mellow_onboarding.connection.chosen': 'You have chosen to sync as {0}, you will be able to change this later.',
		'mellow_onboarding.connection.summary': 'Connect your {0} Account to unlock roles, and more! ({1} actions)',
		'mellow_onboarding.connection.accounts': '{0} Accounts',
		'mellow_onboarding.done': 'You may now close this page, and return to Discord.',

		'mellow_sync_action.type.0': 'Give Roles',
		'mellow_sync_action.type.0.full': 'Gives Roles',
		'mellow_sync_action.type.0.can_remove': 'Removable',
		'mellow_sync_action.type.1': 'Ban from Server',
		'mellow_sync_action.type.1.full': 'Bans from Server',
		'mellow_sync_action.type.2': 'Kick from Server',
		'mellow_sync_action.type.2.full': 'Kicks from Server',
		'mellow_sync_action.type.3': 'Cancel Sync',
		'mellow_sync_action.type.3.full': 'Cancels Sync',
		'mellow_sync_action.creator': 'Created by',
		'mellow_sync_action.edited': ', edited by',
		'mellow_sync_action.view_mode.0': 'Default View',
		'mellow_sync_action.view_mode.1': 'Compact View',
		'mellow_sync_action.requirement.0': 'Must have an account',
		'mellow_sync_action.requirement.1': 'Must have a group role',
		'mellow_sync_action.requirement.1.select': 'Group Roles',
		'mellow_sync_action.requirement.2': 'Must have a group rank in range',
		'mellow_sync_action.requirement.3': 'Must be in a group',
		'mellow_sync_action.requirement.4': 'Must be friends with someone',
		'mellow_sync_action.requirement.5': 'Must meet another action',
		'mellow_sync_action.requirement.6': 'Must be in a Team',
		'mellow_sync_action.requirement.7': 'Must be in a Group',
		'mellow_sync_action.requirement.8': 'Must own a copy of an Asset',
		'mellow_sync_action.requirement.8.id': 'Asset ID',
		'mellow_sync_action.requirement.9': 'Must have a Badge',
		'mellow_sync_action.requirement.9.id': 'Badge ID',
		'mellow_sync_action.requirement.10': 'Must have a Pass',
		'mellow_sync_action.requirement.10.id': 'Pass ID',
		'mellow_sync_action.requirement.11': 'Must be in an Organisation',
		'mellow_sync_action.requirements_type.0': 'Must meet all',
		'mellow_sync_action.requirements_type.1': 'Must meet at least one',
		'mellow_sync_action.requirements': '{0} Requirement{0|s}',
		'mellow_sync_action.requirements.with': 'with {0} requirement{0|s}',
		'mellow_sync_action.explanation.0': 'Assigns {0.items.length} Discord Role{0.items.length|s} to members',
		'mellow_sync_action.explanation.1': 'Permanently bans members',
		'mellow_sync_action.explanation.2': 'Kicks members',
		'mellow_sync_action.explanation.3': 'Cancels Server Profile Sync',
		'mellow_sync_action.explanation.end.0': ' if they meet {0} requirement{0|s}.',
		'mellow_sync_action.explanation.end.1': ' if they meet at least one of {0} requirement{0|s}.',

		'docs': 'Documentation',
		'docs.articles.api': 'API',
		'docs.articles.mellow': 'mellow',
		'docs.articles.mellow.quickstart': 'Quickstart',
		'docs.articles.platform': 'Platform',
		'docs.articles.platform.account.connections': 'Connections',

		'reference': 'Reference',
		'reference.articles.rest-api': 'Rest API',
		'reference.articles.rest-api.team': 'Team',
		'reference.articles.rest-api.user': 'User',

		'navigation.settings.profile': 'Profile',
		'navigation.settings.teams': 'Teams',
		'navigation.settings.mellow.servers': 'mellow',
		'navigation.settings.account': 'Settings',
		'navigation.team_settings.members': 'Members',
		'navigation.team_settings.roles': 'Roles',

		'side_navigation.settings.account': 'General',
		'side_navigation.settings.account.connections': 'Connections',
		'side_navigation.settings.account.security': 'Security',
		'side_navigation.team_settings.applications': 'Applications',
		'side_navigation.team_settings.action_log': 'Action Log',

		'error.page': '(。>︿<)_θ',
		'error.page2': 'oh noes, something\'s wrong!',
		'error.page3': 'Code {0} • ″{1}‶',
		'error.unknown': 'An unknown error occurred.',

		'request_error.0': 'There were issues with your request, please change your input and try again.',
		'request_error.1': 'You are not signed-in, please refresh the page.',
		'request_error.2': 'An unexpected error occurred while updating our database, please try again in a few minutes.',
		'request_error.3': 'One of the requirements is missing its group value.',
		'request_error.4': 'Please check your internet connection, or refresh the page, and try again.',
		'request_error.5': 'An unknown error occurred while making the request, please try again later...',
		'request_error.6': 'You don\'t have permission to access this resource.',
		'request_error.7': 'An unexpected error occurred while making a request to an external source, please try again in a few minutes.',
		'request_error.8': 'The requested resource could not be found.',
		'request_error.9': 'You do not have permission to complete this action.',
		'request_error.10': 'This name is too short, it must be at least 3 characters long.',
		'request_error.11': 'Please refresh the page, restart your browser, or check your internet connection and try again.',
		'request_error.12': 'This feature has been temporarily disabled, please try again later...',
		'request_error.13': 'The query you entered was invalid, please change your input and try again.',
		'request_error.14': 'This name is too long, it must be at most 20 characters long.',
		'request_error.unauthorised': 'You don\'t have permission to access this resource.',
		'request_error.invalid_body': 'There were issues with your request, please change your input and try again.',
		'request_error.database_error': 'An unexpected error occurred while accessing our database, please try again in a few minutes.',
		'request_error.profile_exists': 'Your account already has a profile set-up, try refreshing.',
		'request_error.no_permission': 'You do not have permission to complete this action.',
		'request_error.team_exists': 'Another team already exists with that handle.',
		'request_error.team_not_found': 'This team could not be found.',
		'request_error.cannot_leave_team': 'You cannot leave this team as its current owner.',
		'request_error.invalid_id': 'An identifier associated with this request was deemed invalid, please file a bug report.',
		'request_error.username_taken': 'apologies, that username is taken! just a bit more creativity!!!',
		'request_error.no_permission_target_role': 'You do not have permission to manage this role.',
		'request_error.not_found': 'The requested resource could not be found.',
		'request_error.user_not_found': 'The requested user does not exist.',
		'request_error.username_not_found': 'No account exists with that username, did you make a typo?',
		'request_error.security_device_not_found': 'The requested security device does not exist.',
		'request_error.user_connection_not_found': 'The requested user connection does not exist.',
		'request_error.feature_disabled': 'This feature has been temporarily disabled, please try again later...',
		'request_error.missing_signature': 'Failed to authenticate, security signature is missing, please sign out.',
		'request_error.invalid_signature': 'Failed to authenticate, security signature is invalid, please sign out.',
		'request_error.missing_device_key': 'Your session is out-of-date, and can no longer be used for security reasons, please sign out.',
		'request_error.title': 'REQUEST ERROR',
		'request_error.zod': 'ISSUES',

		'zod_issue.invalid_type': 'Received type is incorrect.',
		'zod_issue.invalid_literal': 'Received literal is incorrect.',
		'zod_issue.unrecognized_keys': 'Contains unrecognisable data.',
		'zod_issue.invalid_union': 'Received data is invalid.',
		'zod_issue.invalid_union_discriminator': 'Received data is invalid.',
		'zod_issue.invalid_enum_value': 'Received invalid value.',
		'zod_issue.invalid_arguments': 'Contains invalid data.',
		'zod_issue.invalid_return_type': 'Received data is invalid.',
		'zod_issue.invalid_date': 'Invalid date.',
		'zod_issue.invalid_string': 'Contains invalid characters.',
		'zod_issue.too_small': 'Contains less than {0.minimum} character{0.minimum|s}.',
		'zod_issue.too_big': 'Contains more than {0.maximum} character{0.maximum|s}.',
		'zod_issue.invalid_intersection_types': 'Received data is invalid.',
		'zod_issue.not_multiple_of': 'Received data is invalid.',
		'zod_issue.not_finite': 'Received data is invalid.',
		'zod_issue.custom': 'Received data is invalid.',

		'number': '{0|number}',

		'days_ago': '{0|days_ago}',

		'time_ago': '{0|time_ago}',
		'time_ago.0_0': '{0} seconds ago',
		'time_ago.0_1': 'now',
		'time_ago.1_0': '{0} minutes ago',
		'time_ago.1_1': '{0} minute ago',
		'time_ago.2_0': '{0} hours ago',
		'time_ago.2_1': '{0} hour ago',
		'time_ago.3_0': '{0} days ago at {1}:{2} {3}',
		'time_ago.3_1': 'yesterday',
		'time_ago.4_0': '{0} weeks ago',
		'time_ago.4_1': 'last week',
		'time_ago.5_0': '{0} months ago',
		'time_ago.5_1': 'last month',
		'time_ago.6_0': '{0} years ago',
		'time_ago.6_1': 'last year',
		'time_ago.created': 'Created {0|time_ago}',
		'time_ago.updated': 'Updated {0|time_ago}',
		'time_ago.archived': 'Archived {0|time_ago}',

		'footer.oss': 'HAKUMI is',
		'footer.oss.link': 'open-source',
		'footer.legal': 'Words Words',
		'footer.legal.terms': 'Terms of Service',
		'footer.legal.privacy': 'Privacy Policy',
		'footer.resources': 'Resources',
		'footer.resources.status': 'Status',
		'footer.community': 'Community',

		'modal.team_invite': 'You have been invited to join',
		'modal.team_invite.summary': 'A member of {0} has invited you to join them!',
		'modal.team_invite.welcome': 'Welcome to the team!',
		'modal.team_invite.welcome.summary': 'You are now a member of {0}, woo-hoo!',
		'modal.unsaved_changes': 'You have unsaved changes!',
		'modal.unsaved_changes.saving': 'Saving...',
		'modal.unsaved_changes.error': 'Failed to save changes.',
		'modal.setup_profile': 'Create your profile',
		'modal.setup_profile.summary': 'Last step! It\'s time to set-up your public profile...',
		'modal.setup_profile.welcome': 'Welcome to HAKUMI!',
		'modal.setup_profile.welcome.summary': 'You are now a fellow member of our little community, neat!'
	}
};